// All data parsed from the full TeamBuildr API export
// Source: test-data/teambuildr-full-export-5-athletes.json (37 MB)
// Extracted: 2026-02-17 from account 20731
// Full history: May 2021 — Feb 2026 (Hannah & Maddy), May 2025 — Feb 2026 (Matt, Chris, Michael)

export const extractionStats = {
  athletes: 5,
  totalDates: 2033,
  apiCalls: 4066,
  errors: 0,
  dataSize: "37 MB",
  accountId: 20731,
  dateRange: {
    start: "2021-05-17",
    end: "2026-02-17",
  },
  totalTonnageKg: 6698942,
  totalSets: 16552,
  totalReps: 105616,
  totalWorkoutItems: 12437,
  uniqueExercises: 136,
  totalPRs: 1806,
};

export const athleteData = [
  {
    id: 3534583,
    name: "Matt Alldian",
    group: "CMM Punk",
    dates: 114,
    completionRate: 51,
    tonnageKg: 248434,
    totalSets: 904,
    totalReps: 5493,
    avgSessionMinutes: 50,
    prCount: 69,
    topExercises: [
      { name: "Comp Squat", count: 100 },
      { name: "1 Count Paused Bench", count: 78 },
      { name: "Comp bench", count: 74 },
      { name: "Conventional Deadlift", count: 63 },
      { name: "3 Count Paused Bench", count: 43 },
    ],
    dateRange: { start: "2025-05-05", end: "2026-02-14" },
    prs: [
      { date: "2025-05-05", exercise: "Comp Squat", value: 96 },
      { date: "2025-05-08", exercise: "Comp Deadlift", value: 100 },
      { date: "2025-11-10", exercise: "Comp Squat", value: 130 },
      { date: "2026-01-19", exercise: "Comp Squat", value: 139 },
      { date: "2026-01-29", exercise: "Comp bench", value: 84 },
    ],
  },
  {
    id: 3534582,
    name: "Chris Laakko",
    group: "CMM Punk",
    dates: 115,
    completionRate: 32,
    tonnageKg: 250247,
    totalSets: 515,
    totalReps: 3331,
    avgSessionMinutes: 54,
    prCount: 36,
    topExercises: [
      { name: "Comp Squat", count: 98 },
      { name: "1 Count Paused Bench", count: 78 },
      { name: "Comp bench", count: 73 },
      { name: "Conventional Deadlift", count: 64 },
      { name: "3 Count Paused Bench", count: 42 },
    ],
    dateRange: { start: "2025-05-05", end: "2026-02-14" },
    prs: [
      { date: "2025-05-05", exercise: "Comp Squat", value: 149 },
      { date: "2025-05-08", exercise: "Comp Deadlift", value: 175 },
      { date: "2025-10-27", exercise: "Comp Squat", value: 179 },
      { date: "2025-11-03", exercise: "Comp Squat", value: 183 },
      { date: "2025-12-08", exercise: "1 Count Paused Bench", value: 111 },
    ],
  },
  {
    id: 3534584,
    name: "Michael Odermatt",
    group: "CMM Punk",
    dates: 113,
    completionRate: 26,
    tonnageKg: 121147,
    totalSets: 466,
    totalReps: 2465,
    avgSessionMinutes: 51,
    prCount: 47,
    topExercises: [
      { name: "Comp Squat", count: 97 },
      { name: "1 Count Paused Bench", count: 76 },
      { name: "Comp bench", count: 72 },
      { name: "Conventional Deadlift", count: 62 },
      { name: "3 Count Paused Bench", count: 42 },
    ],
    dateRange: { start: "2025-05-05", end: "2026-02-14" },
    prs: [
      { date: "2025-05-05", exercise: "Comp bench", value: 47 },
      { date: "2025-05-08", exercise: "Comp Deadlift", value: 60 },
      { date: "2025-10-27", exercise: "Comp Squat", value: 130 },
      { date: "2025-12-11", exercise: "Comp bench", value: 76 },
      { date: "2026-01-12", exercise: "1 Count Paused Bench", value: 77.5 },
    ],
  },
  {
    id: 1211113,
    name: "Hannah Jenny",
    group: "Joe's Athletes",
    dates: 899,
    completionRate: 59,
    tonnageKg: 2458751,
    totalSets: 6076,
    totalReps: 31101,
    avgSessionMinutes: 97,
    prCount: 996,
    topExercises: [
      { name: "Comp bench", count: 866 },
      { name: "Comp Squat", count: 718 },
      { name: "Sumo Deadlift", count: 410 },
      { name: "Tricep Extension", count: 362 },
      { name: "Lat Pull-down", count: 217 },
    ],
    dateRange: { start: "2021-05-17", end: "2026-02-15" },
    prs: [
      { date: "2021-09-17", exercise: "Comp Deadlift", value: 184 },
      { date: "2021-09-29", exercise: "Back Squat", value: 146 },
      { date: "2023-04-08", exercise: "Comp Squat", value: 155.5 },
      { date: "2024-11-02", exercise: "Comp bench", value: 102 },
      { date: "2025-10-25", exercise: "Sumo Deadlift", value: 188 },
    ],
  },
  {
    id: 1207702,
    name: "Maddy Corman",
    group: "Joe's Athletes",
    dates: 792,
    completionRate: 74,
    tonnageKg: 3620363,
    totalSets: 8591,
    totalReps: 63226,
    avgSessionMinutes: 93,
    prCount: 658,
    topExercises: [
      { name: "Comp bench", count: 642 },
      { name: "Comp Squat", count: 546 },
      { name: "Comp Deadlift", count: 251 },
      { name: "Tricep Extension", count: 248 },
      { name: "Lat Pull-down", count: 158 },
    ],
    dateRange: { start: "2021-05-18", end: "2026-02-17" },
    prs: [
      { date: "2021-08-31", exercise: "Comp Squat", value: 132 },
      { date: "2021-09-05", exercise: "Comp Deadlift", value: 155 },
      { date: "2023-10-21", exercise: "Comp Squat", value: 168 },
      { date: "2024-03-09", exercise: "Comp bench", value: 102.5 },
      { date: "2025-12-14", exercise: "Comp Deadlift", value: 185 },
    ],
  },
];

export const schemaGaps = [
  {
    id: 1,
    gap: "No WorkoutSession model",
    spec: "01-data-models",
    teambuildrField: "sessionDurationInSeconds, completion status per date",
    recommendation: "Add WorkoutSession model tracking session date, duration, completion status per athlete per date",
    priority: "Critical" as const,
  },
  {
    id: 2,
    gap: "No MaxSnapshot model",
    spec: "01-data-models",
    teambuildrField: "workingMax + generatedMax with timestamps",
    recommendation: "Add MaxSnapshot model for tracking working max + generated max at time of workout",
    priority: "Critical" as const,
  },
  {
    id: 3,
    gap: "No superset grouping",
    spec: "01-data-models",
    teambuildrField: "groupingLetter + groupingColorCode",
    recommendation: "Add supersetGroup (letter) and supersetColor to WorkoutExercise",
    priority: "High" as const,
  },
  {
    id: 4,
    gap: "No unilateral tracking",
    spec: "01-data-models",
    teambuildrField: "eachSide boolean",
    recommendation: "Add isUnilateral boolean to WorkoutExercise",
    priority: "Medium" as const,
  },
  {
    id: 5,
    gap: "No rest/tempo fields",
    spec: "01-data-models",
    teambuildrField: "additionalInformation (free-text)",
    recommendation: "Add restTimeSeconds and tempo to WorkoutExercise",
    priority: "Medium" as const,
  },
  {
    id: 6,
    gap: "No opt-out tracking",
    spec: "06-athlete-training-log",
    teambuildrField: "optedOut, optedOutReason, coachCompletionOnly",
    recommendation: "Add opt-out reason and coach-completion fields",
    priority: "High" as const,
  },
  {
    id: 7,
    gap: "No session duration",
    spec: "06-athlete-training-log",
    teambuildrField: "sessionDurationInSeconds",
    recommendation: "Track session start/end time and duration",
    priority: "High" as const,
  },
  {
    id: 8,
    gap: "No PR source tracking",
    spec: "07-progress-analytics",
    teambuildrField: "workingMax vs generatedMax",
    recommendation: "Track whether max came from workout auto-capture or manual entry",
    priority: "Medium" as const,
  },
  {
    id: 9,
    gap: "Missing exercise types",
    spec: "05-exercise-library",
    teambuildrField: "L, S, C, Sc, W, N type codes",
    recommendation: "Add SAQ+C, Circuit, Science, Warm-Up, Notes types beyond just Lift",
    priority: "Critical" as const,
  },
  {
    id: 10,
    gap: "No migration endpoint",
    spec: "(none)",
    teambuildrField: "Full REST API with structured data",
    recommendation: "Add /api/import/teambuildr endpoint to implementation plan",
    priority: "High" as const,
  },
];

export const apiEndpoints = [
  {
    method: "GET",
    path: "/accounts/{id}/users",
    description: "List account users (athletes/coaches)",
    params: "userType=0 (athletes), userType=1 (coaches)",
    tested: true,
  },
  {
    method: "GET",
    path: "/accounts/{id}/users/{userId}/workouts/overview",
    description: "Workout completion overview for date range",
    params: "dateRangeStart, dateRangeEnd (max 120 days)",
    tested: true,
  },
  {
    method: "GET",
    path: "/accounts/{id}/users/{userId}/workouts/{date}",
    description: "Full workout detail for a specific date",
    params: "None (date in path)",
    tested: true,
  },
  {
    method: "GET",
    path: "/accounts/{id}/users/{userId}/workouts/{date}/summary",
    description: "Session summary with tonnage and PRs",
    params: "None",
    tested: true,
  },
  {
    method: "GET",
    path: "/accounts/{id}/users/{userId}/day-based-workouts",
    description: "Day-based program workout assignments",
    params: "None",
    tested: true,
  },
];

export const exerciseTypes = [
  { code: "L", name: "Lift", description: "Traditional strength exercises with weight/reps tracking", example: "Comp Squat, Bench Press" },
  { code: "S", name: "SAQ+C", description: "Speed, Agility, Quickness + Conditioning", example: "Shuttle Run, Box Jumps" },
  { code: "C", name: "Circuit", description: "Circuit-based exercises with timed intervals", example: "AMRAP circuits" },
  { code: "N", name: "Notes", description: "Coach notes and non-exercise items", example: "Session notes, instructions" },
  { code: "W", name: "Warm-Up", description: "Warm-up activities and mobility work", example: "Foam rolling, band work" },
];

// Real sample: Matt Alldian, Jan 19 2026, Comp Squat — PR day (132 → 139 kg generated max)
// placeholder = prescribed by coach, value = what athlete actually entered
export const sampleWorkoutItem = {
  date: "2026-01-19",
  athlete: "Matt Alldian",
  exercise: { name: "Comp Squat", type: "L", typeDescription: "LIFT" },
  coachNotes: "Work up to a double at RPE 8. Drop 12-15r% for the last two",
  tableHeaders: ["Weight", "Reps", "Peak Velocity"],
  sets: [
    { set: 1, prescribed: { weight: 125, reps: 2, percentage: 95 }, actual: { weight: 130, reps: 2 } },
    { set: 2, prescribed: { weight: 106, reps: 4, percentage: 80 }, actual: { weight: 110, reps: 4 } },
    { set: 3, prescribed: { weight: 106, reps: 4, percentage: 80 }, actual: { weight: 110, reps: 4 } },
  ],
  workingMax: { value: 132, date: "2026-01-12" },
  generatedMax: { value: 139, date: "2026-01-19", isCurrentMax: true },
  supersetGroup: null,
  isUnilateral: false,
};
