import type { Section, Question } from './types';

export const sections: Section[] = [
  {
    id: 'welcome',
    title: 'Welcome & Trainer Profile',
    description: 'Tell us about your role and organization.',
    order: 0,
  },
  {
    id: 'current-setup',
    title: 'Current Setup',
    description: 'How are you currently managing training programs?',
    order: 1,
  },
  {
    id: 'pain-points',
    title: 'Pain Points',
    description: 'What challenges do you face in your current workflow?',
    order: 2,
  },
  {
    id: 'features',
    title: 'Must-Have vs Nice-to-Have Features',
    description: 'Help us prioritize the features that matter most to you.',
    order: 3,
  },
  {
    id: 'budget',
    title: 'Budget',
    description: 'Understanding your budget helps us find the right fit.',
    order: 4,
  },
  {
    id: 'technical',
    title: 'Technical Requirements',
    description: 'Mobile, integrations, compliance, and more.',
    order: 5,
  },
  {
    id: 'athlete-model',
    title: 'Athlete Interaction Model',
    description: 'How do you and your athletes interact day-to-day?',
    order: 6,
  },
  {
    id: 'data-analytics',
    title: 'Data & Analytics',
    description: 'What data do you need to capture and who needs to see it?',
    order: 7,
  },
  {
    id: 'communication',
    title: 'Communication',
    description: 'Messaging, notifications, and staying in touch.',
    order: 8,
  },
  {
    id: 'workflows',
    title: 'Specific Workflows',
    description: 'Program design, periodization, testing, and more.',
    order: 9,
  },
  {
    id: 'priorities',
    title: 'Priorities & Final Thoughts',
    description: 'Wrap up by ranking what matters most.',
    order: 10,
  },
];

export const questions: Question[] = [
  // ── Section 0: Welcome & Trainer Profile ──────────────────────────
  {
    id: 'role',
    sectionId: 'welcome',
    type: 'single-choice',
    title: 'What best describes your primary role?',
    description: 'Select the role that most closely matches your day-to-day responsibilities.',
    required: true,
    options: [
      { value: 'sc-coach', label: 'Strength & Conditioning Coach' },
      { value: 'personal-trainer', label: 'Personal Trainer' },
      { value: 'sports-scientist', label: 'Sports Scientist' },
      { value: 'athletic-director', label: 'Athletic Director' },
      { value: 'head-coach', label: 'Head / Sport Coach' },
      { value: 'rehab-specialist', label: 'Rehab / Sports Medicine Specialist' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'role-other',
    sectionId: 'welcome',
    type: 'text',
    title: 'Please describe your role.',
    placeholder: 'e.g. Performance Director',
    required: true,
    condition: { questionId: 'role', operator: 'equals', value: 'other' },
  },
  {
    id: 'org-type',
    sectionId: 'welcome',
    type: 'single-choice',
    title: 'What type of organization do you work with?',
    required: true,
    options: [
      { value: 'high-school', label: 'High School' },
      { value: 'college', label: 'College / University' },
      { value: 'pro-team', label: 'Professional Team' },
      { value: 'private-gym', label: 'Private Gym / Training Facility' },
      { value: 'military', label: 'Military / Tactical' },
      { value: 'independent', label: 'Independent / Freelance' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'org-type-other',
    sectionId: 'welcome',
    type: 'text',
    title: 'Please describe your organization type.',
    placeholder: 'e.g. Olympic Training Center',
    required: true,
    condition: { questionId: 'org-type', operator: 'equals', value: 'other' },
  },
  {
    id: 'athlete-count',
    sectionId: 'welcome',
    type: 'single-choice',
    title: 'How many athletes or clients do you currently train?',
    required: true,
    options: [
      { value: '1-10', label: '1 - 10' },
      { value: '11-30', label: '11 - 30' },
      { value: '31-75', label: '31 - 75' },
      { value: '76-150', label: '76 - 150' },
      { value: '150+', label: '150+' },
    ],
  },

  // ── Section 1: Current Setup ──────────────────────────────────────
  {
    id: 'using-platform',
    sectionId: 'current-setup',
    type: 'single-choice',
    title: 'Are you currently using a training management platform?',
    required: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  {
    id: 'which-platform',
    sectionId: 'current-setup',
    type: 'single-choice',
    title: 'Which platform are you currently using?',
    condition: { questionId: 'using-platform', operator: 'equals', value: 'yes' },
    required: true,
    options: [
      { value: 'teambuildr', label: 'TeamBuildr' },
      { value: 'bridge-athletic', label: 'Bridge Athletic' },
      { value: 'volt', label: 'Volt Athletics' },
      { value: 'trainheroic', label: 'TrainHeroic' },
      { value: 'strengthcoach', label: 'StrengthCoach.com' },
      { value: 'excel-sheets', label: 'Excel / Google Sheets' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'which-platform-other',
    sectionId: 'current-setup',
    type: 'text',
    title: 'Which platform are you using?',
    placeholder: 'Platform name',
    required: true,
    condition: { questionId: 'which-platform', operator: 'equals', value: 'other' },
  },
  {
    id: 'platform-satisfaction',
    sectionId: 'current-setup',
    type: 'scale',
    title: 'How satisfied are you with your current platform?',
    description: 'Rate from 1 (very dissatisfied) to 10 (very satisfied).',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'Very dissatisfied', max: 'Very satisfied' },
    condition: { questionId: 'using-platform', operator: 'equals', value: 'yes' },
    required: true,
  },
  {
    id: 'switch-trigger',
    sectionId: 'current-setup',
    type: 'textarea',
    title: 'What triggered you to look for alternatives?',
    placeholder: 'e.g. Missing features, high cost, poor support...',
    condition: { questionId: 'using-platform', operator: 'equals', value: 'yes' },
  },
  {
    id: 'using-spreadsheets',
    sectionId: 'current-setup',
    type: 'single-choice',
    title: 'Are you currently using spreadsheets, paper, or whiteboards to manage programming?',
    condition: { questionId: 'using-platform', operator: 'equals', value: 'no' },
    required: true,
    options: [
      { value: 'spreadsheets', label: 'Yes, spreadsheets (Excel / Google Sheets)' },
      { value: 'paper', label: 'Yes, paper / whiteboards' },
      { value: 'both', label: 'A mix of spreadsheets and paper' },
      { value: 'nothing', label: 'No formal system' },
    ],
  },

  // ── Section 2: Pain Points ────────────────────────────────────────
  {
    id: 'biggest-frustrations',
    sectionId: 'pain-points',
    type: 'multi-choice',
    title: 'What are your biggest frustrations with your current workflow?',
    description: 'Select all that apply.',
    required: true,
    options: [
      { value: 'time-programming', label: 'Too much time writing programs', description: 'Hours spent building workouts in spreadsheets or on paper' },
      { value: 'no-autoregulation', label: 'No autoregulation support', description: 'Cannot adjust loads based on daily readiness or velocity' },
      { value: 'poor-tracking', label: 'Poor progress tracking', description: 'Hard to see trends, PRs, or long-term development' },
      { value: 'athlete-compliance', label: 'Low athlete compliance / engagement', description: 'Athletes don\'t log or follow programs consistently' },
      { value: 'no-team-view', label: 'No weight room overview', description: 'Cannot see all athletes\' sessions at a glance on a TV or display' },
      { value: 'data-silos', label: 'Data trapped in silos', description: 'Information scattered across apps, sheets, and paper' },
      { value: 'reporting', label: 'Hard to generate reports', description: 'Difficult to share progress with coaches, admin, or parents' },
      { value: 'scaling', label: 'Doesn\'t scale', description: 'What works for 10 athletes breaks at 50 or 100+' },
    ],
  },
  {
    id: 'most-lacking-features',
    sectionId: 'pain-points',
    type: 'textarea',
    title: 'What features or capabilities are most lacking in your current setup?',
    placeholder: 'Describe the gaps you experience day-to-day...',
    required: true,
  },
  {
    id: 'time-consuming-tasks',
    sectionId: 'pain-points',
    type: 'multi-choice',
    title: 'Which manual tasks consume the most of your time?',
    description: 'Select all that apply.',
    required: true,
    options: [
      { value: 'writing-programs', label: 'Writing / copying training programs' },
      { value: 'adjusting-loads', label: 'Manually adjusting loads and percentages' },
      { value: 'entering-data', label: 'Entering data from paper logs' },
      { value: 'building-reports', label: 'Building reports or summaries' },
      { value: 'communicating-changes', label: 'Communicating program changes to athletes' },
      { value: 'managing-rosters', label: 'Managing rosters and groups' },
      { value: 'tracking-testing', label: 'Tracking testing and assessment results' },
    ],
  },

  // ── Section 3: Must-Have vs Nice-to-Have Features ─────────────────
  {
    id: 'must-have-features',
    sectionId: 'features',
    type: 'multi-choice',
    title: 'Which features are MUST-HAVES for you?',
    description: 'Select every feature you consider essential. You cannot go without these.',
    required: true,
    options: [
      { value: 'apre-autoregulation', label: 'APRE / Autoregulation', description: 'Auto-adjust loads based on rep performance' },
      { value: 'vbt', label: 'Velocity-Based Training (VBT)', description: 'Integrate bar speed data into programming' },
      { value: 'weight-room-view', label: 'Weight Room View / TV Display', description: 'Large-screen display showing live session status' },
      { value: 'wearable-integration', label: 'Wearable Integration', description: 'Sync with heart rate monitors, GPS, recovery wearables' },
      { value: 'readiness-monitoring', label: 'Readiness / Wellness Monitoring', description: 'Daily check-ins for sleep, soreness, stress, etc.' },
      { value: 'exercise-library', label: 'Exercise Video Library', description: 'Built-in or custom video demos for exercises' },
      { value: 'workout-builder', label: 'Workout Builder', description: 'Drag-and-drop or structured program design tool' },
      { value: 'team-management', label: 'Team / Roster Management', description: 'Organize athletes by team, position, group' },
      { value: 'analytics', label: 'Progress Analytics & Dashboards', description: 'Charts, trends, and athlete progress views' },
      { value: 'mobile-app', label: 'Mobile App', description: 'Native or responsive app for coaches and athletes' },
      { value: 'testing-assessment', label: 'Testing & Assessment', description: 'Track combine, max testing, body composition, etc.' },
      { value: 'periodization', label: 'Periodization Tools', description: 'Built-in support for mesocycles, phases, blocks' },
    ],
  },
  {
    id: 'nice-to-have-features',
    sectionId: 'features',
    type: 'multi-choice',
    title: 'Which features would be NICE-TO-HAVE?',
    description: 'These would be great but are not dealbreakers.',
    options: [
      { value: 'apre-autoregulation', label: 'APRE / Autoregulation' },
      { value: 'vbt', label: 'Velocity-Based Training (VBT)' },
      { value: 'weight-room-view', label: 'Weight Room View / TV Display' },
      { value: 'wearable-integration', label: 'Wearable Integration' },
      { value: 'readiness-monitoring', label: 'Readiness / Wellness Monitoring' },
      { value: 'exercise-library', label: 'Exercise Video Library' },
      { value: 'workout-builder', label: 'Workout Builder' },
      { value: 'team-management', label: 'Team / Roster Management' },
      { value: 'analytics', label: 'Progress Analytics & Dashboards' },
      { value: 'mobile-app', label: 'Mobile App' },
      { value: 'testing-assessment', label: 'Testing & Assessment' },
      { value: 'periodization', label: 'Periodization Tools' },
    ],
  },
  {
    id: 'dealbreakers',
    sectionId: 'features',
    type: 'textarea',
    title: 'Are there any absolute dealbreakers?',
    description: 'Features or limitations that would immediately disqualify a platform.',
    placeholder: 'e.g. "No mobile app is a dealbreaker" or "Must support offline use"',
  },

  // ── Section 4: Budget ─────────────────────────────────────────────
  {
    id: 'monthly-budget',
    sectionId: 'budget',
    type: 'single-choice',
    title: 'What is your approximate monthly software budget?',
    required: true,
    options: [
      { value: 'under-50', label: 'Under $50/mo' },
      { value: '50-100', label: '$50 - $100/mo' },
      { value: '100-250', label: '$100 - $250/mo' },
      { value: '250-500', label: '$250 - $500/mo' },
      { value: '500-1000', label: '$500 - $1,000/mo' },
      { value: 'over-1000', label: 'Over $1,000/mo' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
  },
  {
    id: 'pricing-model',
    sectionId: 'budget',
    type: 'single-choice',
    title: 'Which pricing model do you prefer?',
    required: true,
    options: [
      { value: 'per-athlete', label: 'Per-athlete pricing', description: 'Pay based on the number of athletes on the platform' },
      { value: 'flat-rate', label: 'Flat monthly rate', description: 'One price regardless of athlete count' },
      { value: 'tiered', label: 'Tiered plans', description: 'Different tiers based on features or athlete count' },
      { value: 'no-preference', label: 'No preference' },
    ],
  },
  {
    id: 'hardware-budget',
    sectionId: 'budget',
    type: 'single-choice',
    title: 'Do you have budget for hardware such as VBT sensors, TV displays, or tablets?',
    options: [
      { value: 'yes-significant', label: 'Yes, significant budget available' },
      { value: 'yes-limited', label: 'Yes, but limited' },
      { value: 'no', label: 'No hardware budget' },
      { value: 'already-have', label: 'Already have hardware in place' },
    ],
  },

  // ── Section 5: Technical Requirements ─────────────────────────────
  {
    id: 'mobile-importance',
    sectionId: 'technical',
    type: 'scale',
    title: 'How important is mobile access for your coaches and athletes?',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'Not important', max: 'Essential' },
    required: true,
  },
  {
    id: 'offline-needed',
    sectionId: 'technical',
    type: 'single-choice',
    title: 'Do you need offline capability?',
    description: 'Can athletes or coaches use the app without internet access (e.g., in a weight room with poor WiFi)?',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, offline is critical' },
      { value: 'nice', label: 'Nice to have but not essential' },
      { value: 'no', label: 'No, we always have connectivity' },
    ],
  },
  {
    id: 'integrations',
    sectionId: 'technical',
    type: 'multi-choice',
    title: 'Which integrations are important to you?',
    description: 'Select all systems you would want the platform to connect with.',
    options: [
      { value: 'hudl', label: 'Hudl', description: 'Video analysis platform' },
      { value: 'arms', label: 'ARMS / Compliance Software', description: 'NCAA compliance tracking' },
      { value: 'sis', label: 'Student Information System (SIS)', description: 'Academic / enrollment data' },
      { value: 'whoop', label: 'WHOOP', description: 'Recovery and strain wearable' },
      { value: 'garmin', label: 'Garmin', description: 'GPS and heart rate devices' },
      { value: 'apple-health', label: 'Apple Health / Google Fit', description: 'Consumer health platforms' },
      { value: 'catapult', label: 'Catapult / GPS Tracking', description: 'Athlete monitoring systems' },
      { value: 'nutrition', label: 'Nutrition Apps (MyFitnessPal, Fueling, etc.)' },
      { value: 'ehr', label: 'EHR / Medical Records' },
      { value: 'none', label: 'No integrations needed' },
    ],
  },
  {
    id: 'compliance-needs',
    sectionId: 'technical',
    type: 'multi-choice',
    title: 'Do you have any compliance requirements?',
    description: 'Select all that apply to your organization.',
    options: [
      { value: 'ferpa', label: 'FERPA', description: 'Student education records privacy (US)' },
      { value: 'hipaa', label: 'HIPAA', description: 'Health information privacy (US)' },
      { value: 'gdpr', label: 'GDPR', description: 'Data protection (EU)' },
      { value: 'ncaa', label: 'NCAA Compliance', description: 'Athletic eligibility and CARA hours' },
      { value: 'none', label: 'None / Not sure' },
    ],
  },
  {
    id: 'sso-needs',
    sectionId: 'technical',
    type: 'single-choice',
    title: 'Do you require Single Sign-On (SSO) or integration with your organization\'s login system?',
    options: [
      { value: 'yes', label: 'Yes, SSO is required' },
      { value: 'nice', label: 'Nice to have' },
      { value: 'no', label: 'Not needed' },
    ],
  },

  // ── Section 6: Athlete Interaction Model ──────────────────────────
  {
    id: 'coaching-model',
    sectionId: 'athlete-model',
    type: 'single-choice',
    title: 'What is your primary coaching model?',
    required: true,
    options: [
      { value: '1on1', label: '1-on-1 training' },
      { value: 'small-group', label: 'Small group (2-8 athletes)' },
      { value: 'large-team', label: 'Large team (9+ athletes training together)' },
      { value: 'mixed', label: 'Mixed - depends on the day or sport' },
    ],
  },
  {
    id: 'remote-vs-inperson',
    sectionId: 'athlete-model',
    type: 'single-choice',
    title: 'Are your training sessions primarily in-person or remote?',
    required: true,
    options: [
      { value: 'in-person', label: 'All in-person' },
      { value: 'mostly-in-person', label: 'Mostly in-person with some remote' },
      { value: 'hybrid', label: 'Roughly 50/50 hybrid' },
      { value: 'mostly-remote', label: 'Mostly remote' },
      { value: 'all-remote', label: 'All remote / online coaching' },
    ],
  },
  {
    id: 'athlete-tech-comfort',
    sectionId: 'athlete-model',
    type: 'scale',
    title: 'How comfortable are your athletes with technology?',
    description: 'Think about whether they will use a phone app, scan QR codes, log their sets, etc.',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'Not comfortable at all', max: 'Very tech-savvy' },
    required: true,
  },
  {
    id: 'athlete-self-logging',
    sectionId: 'athlete-model',
    type: 'scale',
    title: 'How important is it that athletes can self-log their workouts?',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'Not important (coach logs everything)', max: 'Essential (athletes must self-log)' },
    required: true,
  },

  // ── Section 7: Data & Analytics ───────────────────────────────────
  {
    id: 'key-metrics',
    sectionId: 'data-analytics',
    type: 'multi-choice',
    title: 'Which metrics are most important for you to track?',
    description: 'Select all that apply.',
    required: true,
    options: [
      { value: '1rm', label: 'Estimated / Actual 1RM' },
      { value: 'training-volume', label: 'Training Volume (sets x reps x load)' },
      { value: 'velocity', label: 'Bar Velocity / VBT Metrics' },
      { value: 'bodyweight', label: 'Body Weight / Composition' },
      { value: 'testing-results', label: 'Testing Results (combine, pro agility, etc.)' },
      { value: 'readiness', label: 'Readiness / Wellness Scores' },
      { value: 'attendance', label: 'Attendance / Compliance' },
      { value: 'rpe', label: 'RPE / Session Load' },
      { value: 'injury-status', label: 'Injury / Return-to-Play Status' },
    ],
  },
  {
    id: 'report-audience',
    sectionId: 'data-analytics',
    type: 'multi-choice',
    title: 'Who needs to see reports or dashboards?',
    description: 'Select all stakeholders who need access to data.',
    required: true,
    options: [
      { value: 'athletes', label: 'Athletes' },
      { value: 'sc-coaches', label: 'S&C Coaches' },
      { value: 'sport-coaches', label: 'Sport Coaches / Head Coaches' },
      { value: 'admin', label: 'Athletic Directors / Administrators' },
      { value: 'parents', label: 'Parents / Guardians' },
      { value: 'medical', label: 'Medical / Athletic Training Staff' },
    ],
  },
  {
    id: 'export-formats',
    sectionId: 'data-analytics',
    type: 'multi-choice',
    title: 'What export or reporting formats do you need?',
    options: [
      { value: 'pdf', label: 'PDF Reports' },
      { value: 'csv', label: 'CSV / Excel Export' },
      { value: 'print', label: 'Printable Workout Sheets' },
      { value: 'api', label: 'API Access' },
      { value: 'none', label: 'No export needed - in-app dashboards are fine' },
    ],
  },

  // ── Section 8: Communication ──────────────────────────────────────
  {
    id: 'in-app-messaging',
    sectionId: 'communication',
    type: 'single-choice',
    title: 'Do you need in-app messaging between coaches and athletes?',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, essential' },
      { value: 'nice', label: 'Nice to have' },
      { value: 'no', label: 'No, we use other tools (GroupMe, text, etc.)' },
    ],
  },
  {
    id: 'notification-preferences',
    sectionId: 'communication',
    type: 'multi-choice',
    title: 'What notifications would be valuable?',
    description: 'Select the types of alerts you\'d want the platform to send.',
    options: [
      { value: 'workout-assigned', label: 'New workout assigned' },
      { value: 'workout-completed', label: 'Athlete completed a workout' },
      { value: 'missed-session', label: 'Missed session alerts' },
      { value: 'pr-hit', label: 'PR / personal record achieved' },
      { value: 'readiness-flag', label: 'Low readiness / wellness flag' },
      { value: 'program-reminder', label: 'Upcoming session reminders' },
    ],
  },
  {
    id: 'communication-tools',
    sectionId: 'communication',
    type: 'textarea',
    title: 'What communication tools do you currently use with your athletes?',
    placeholder: 'e.g. GroupMe, text messages, email, team app...',
  },

  // ── Section 9: Specific Workflows ─────────────────────────────────
  {
    id: 'program-design-approach',
    sectionId: 'workflows',
    type: 'single-choice',
    title: 'How do you typically design training programs?',
    required: true,
    options: [
      { value: 'template', label: 'Template-based', description: 'Create a master template and assign it to groups' },
      { value: 'individualized', label: 'Fully individualized', description: 'Each athlete gets a unique program' },
      { value: 'hybrid', label: 'Hybrid', description: 'Templates with individual modifications' },
    ],
  },
  {
    id: 'periodization-models',
    sectionId: 'workflows',
    type: 'multi-choice',
    title: 'Which periodization models do you use or plan to use?',
    description: 'Select all that apply.',
    options: [
      { value: 'linear', label: 'Linear Periodization' },
      { value: 'undulating', label: 'Daily Undulating (DUP)' },
      { value: 'weekly-undulating', label: 'Weekly Undulating' },
      { value: 'block', label: 'Block Periodization' },
      { value: 'conjugate', label: 'Conjugate / Westside' },
      { value: 'concurrent', label: 'Concurrent' },
      { value: 'apre', label: 'APRE (Autoregulatory Progressive Resistance)' },
      { value: 'rpe-based', label: 'RPE-Based Programming' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'vbt-usage',
    sectionId: 'workflows',
    type: 'single-choice',
    title: 'Do you currently use or plan to use Velocity-Based Training (VBT)?',
    required: true,
    options: [
      { value: 'yes-currently', label: 'Yes, I currently use VBT' },
      { value: 'yes-planning', label: 'Planning to implement VBT' },
      { value: 'interested', label: 'Interested but not committed yet' },
      { value: 'no', label: 'No interest in VBT' },
    ],
  },
  {
    id: 'vbt-devices',
    sectionId: 'workflows',
    type: 'multi-choice',
    title: 'Which VBT devices do you use or plan to use?',
    condition: {
      questionId: 'vbt-usage',
      operator: 'includes',
      value: ['yes-currently', 'yes-planning'],
    },
    options: [
      { value: 'gymaware', label: 'GymAware / FLEX' },
      { value: 'tendo', label: 'Tendo Unit' },
      { value: 'push-band', label: 'PUSH Band' },
      { value: 'vitruve', label: 'Vitruve (formerly Speed4Lifts)' },
      { value: 'enode', label: 'Enode Pro' },
      { value: 'repone', label: 'RepOne' },
      { value: 'metric-vbt', label: 'Metric VBT' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'testing-frequency',
    sectionId: 'workflows',
    type: 'single-choice',
    title: 'How often do you conduct formal testing or assessments?',
    required: true,
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly / Each training block' },
      { value: 'biannual', label: 'Twice per year (pre/post season)' },
      { value: 'rarely', label: 'Rarely or never' },
    ],
  },
  {
    id: 'competition-season',
    sectionId: 'workflows',
    type: 'textarea',
    title: 'How do competition seasons affect your programming?',
    description: 'Describe any seasonal considerations, in-season vs off-season differences, etc.',
    placeholder: 'e.g. We reduce volume in-season, focus on maintenance, adjust around game schedules...',
  },

  // ── Section 10: Priorities & Final Thoughts ───────────────────────
  {
    id: 'top-priorities',
    sectionId: 'priorities',
    type: 'ranking',
    title: 'Rank your top 3 priorities for a training platform.',
    description: 'Drag or use arrows to reorder. The top item is your highest priority.',
    required: true,
    options: [
      { value: 'ease-of-use', label: 'Ease of use' },
      { value: 'feature-depth', label: 'Feature depth / power' },
      { value: 'price', label: 'Affordable pricing' },
      { value: 'mobile', label: 'Mobile experience' },
      { value: 'integrations', label: 'Integrations with other tools' },
      { value: 'support', label: 'Customer support & training' },
      { value: 'customization', label: 'Customization / flexibility' },
      { value: 'data-analytics', label: 'Data & analytics' },
      { value: 'athlete-experience', label: 'Athlete-facing experience' },
    ],
  },
  {
    id: 'implementation-timeline',
    sectionId: 'priorities',
    type: 'single-choice',
    title: 'When are you looking to have a platform in place?',
    required: true,
    options: [
      { value: 'asap', label: 'As soon as possible' },
      { value: '1-3-months', label: 'Within 1-3 months' },
      { value: '3-6-months', label: 'Within 3-6 months' },
      { value: '6-12-months', label: 'Within 6-12 months' },
      { value: 'just-exploring', label: 'Just exploring options' },
    ],
  },
  {
    id: 'final-thoughts',
    sectionId: 'priorities',
    type: 'textarea',
    title: 'Any other thoughts, requirements, or questions?',
    description: 'This is your chance to tell us anything else that\'s important to you.',
    placeholder: 'Share anything we may have missed...',
  },
];
