import type { Section, Question } from './types';

export const sections: Section[] = [
  {
    id: 'you',
    title: 'About You & Your Practice',
    description: 'Your coaching identity, who you train, and how your business runs today.',
    order: 0,
  },
  {
    id: 'day-in-life',
    title: 'A Day in Your Coaching Life',
    description: 'Walk us through how you currently program, deliver, and track training.',
    order: 1,
  },
  {
    id: 'athletes',
    title: 'Your Athletes',
    description: 'Who they are, how they interact with you, and what they expect.',
    order: 2,
  },
  {
    id: 'programming',
    title: 'Programming & Methodology',
    description: 'How you design programs, periodize, and use tools like VBT and RPE.',
    order: 3,
  },
  {
    id: 'comp-prep',
    title: 'Competition & Meet Prep',
    description: 'How you prepare athletes for the platform on meet day.',
    order: 4,
  },
  {
    id: 'pain',
    title: 'What\'s Broken Today',
    description: 'The gaps, frustrations, and time sinks in your current workflow.',
    order: 5,
  },
  {
    id: 'dream-platform',
    title: 'Your Dream Platform',
    description: 'If you could build the perfect coaching tool, what would it do?',
    order: 6,
  },
  {
    id: 'business',
    title: 'Business & Growth',
    description: 'Scaling your practice, revenue streams, and brand.',
    order: 7,
  },
  {
    id: 'priorities',
    title: 'Priorities & Tradeoffs',
    description: 'What matters most when you have to choose.',
    order: 8,
  },
];

export const questions: Question[] = [
  // ── Section 0: About You & Your Practice ────────────────────────────
  {
    id: 'coaching-identity',
    sectionId: 'you',
    type: 'multi-choice',
    title: 'Which of these describe what you do? Select all that apply.',
    description: 'We know coaches wear many hats. Check everything that\'s part of your week.',
    required: true,
    options: [
      { value: 'powerlifting-coach', label: 'Powerlifting Coach', description: 'Programming and coaching for competitive powerlifters' },
      { value: '1on1-trainer', label: '1-on-1 Personal Trainer', description: 'Individual training sessions in person' },
      { value: 'remote-coach', label: 'Remote / Online Coach', description: 'Programming delivered to athletes you don\'t see in person' },
      { value: 'group-coach', label: 'Group / Class Coach', description: 'Running group sessions or drop-in training' },
      { value: 'rehab-coach', label: 'Rehab / Return-to-Training Coach', description: 'Working with injured athletes to get them back on the platform' },
      { value: 'meet-director', label: 'Meet Director / Event Organizer', description: 'Organizing and running powerlifting competitions' },
      { value: 'content-creator', label: 'Content Creator / Educator', description: 'Podcast, blog, social media, templates' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'coaching-identity-other',
    sectionId: 'you',
    type: 'text',
    title: 'What else do you do?',
    placeholder: 'e.g. Sports scientist, nutritional coaching...',
    condition: { questionId: 'coaching-identity', operator: 'includes', value: ['other'] },
  },
  {
    id: 'athlete-count',
    sectionId: 'you',
    type: 'single-choice',
    title: 'How many athletes are you actively coaching right now?',
    description: 'Include both in-person and remote clients.',
    required: true,
    options: [
      { value: '1-5', label: '1 - 5' },
      { value: '6-15', label: '6 - 15' },
      { value: '16-30', label: '16 - 30' },
      { value: '31-50', label: '31 - 50' },
      { value: '50+', label: '50+' },
    ],
  },
  {
    id: 'in-person-vs-remote',
    sectionId: 'you',
    type: 'single-choice',
    title: 'What\'s the split between in-person and remote athletes?',
    required: true,
    options: [
      { value: 'all-in-person', label: 'All in-person' },
      { value: 'mostly-in-person', label: 'Mostly in-person, a few remote' },
      { value: 'even-split', label: 'Roughly even split' },
      { value: 'mostly-remote', label: 'Mostly remote, some in-person' },
      { value: 'all-remote', label: 'All remote' },
    ],
  },
  {
    id: 'facility-situation',
    sectionId: 'you',
    type: 'single-choice',
    title: 'What\'s your facility situation?',
    required: true,
    options: [
      { value: 'independent-at-gym', label: 'Independent coach at someone else\'s gym', description: 'You train clients at a gym you don\'t own' },
      { value: 'own-gym', label: 'I own / co-own the gym', description: 'You have your own facility' },
      { value: 'home-gym', label: 'Home gym or garage gym' },
      { value: 'multiple-locations', label: 'I work out of multiple locations' },
      { value: 'fully-remote', label: 'No physical location (fully remote)' },
    ],
  },
  {
    id: 'coaching-solo-or-team',
    sectionId: 'you',
    type: 'single-choice',
    title: 'Are you coaching solo or do you have other coaches working with you?',
    required: true,
    options: [
      { value: 'solo', label: 'Solo — it\'s just me' },
      { value: 'with-partner', label: 'I have a coaching partner or co-coach' },
      { value: 'small-team', label: 'Small team (2-4 coaches)' },
      { value: 'larger-team', label: 'Larger team (5+ coaches)' },
    ],
  },

  // ── Section 1: A Day in Your Coaching Life ──────────────────────────
  {
    id: 'how-write-programs',
    sectionId: 'day-in-life',
    type: 'multi-choice',
    title: 'How do you currently write and deliver training programs?',
    description: 'Select all tools you use.',
    required: true,
    options: [
      { value: 'google-sheets', label: 'Google Sheets / Excel', description: 'Spreadsheets for programming' },
      { value: 'coaching-platform', label: 'Coaching platform (TrainHeroic, TrueCoach, etc.)' },
      { value: 'pdf-docs', label: 'PDF or Word docs', description: 'Written programs sent as documents' },
      { value: 'notes-app', label: 'Notes app (Apple Notes, Notion, etc.)' },
      { value: 'paper', label: 'Paper / whiteboard' },
      { value: 'text-dm', label: 'Text messages or DMs', description: 'Sending workouts via text/Instagram' },
      { value: 'custom-app', label: 'Custom-built tool or app' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'which-coaching-platform',
    sectionId: 'day-in-life',
    type: 'text',
    title: 'Which coaching platform(s) do you use?',
    placeholder: 'e.g. TrainHeroic, TrueCoach, TeamBuildr...',
    condition: { questionId: 'how-write-programs', operator: 'includes', value: ['coaching-platform'] },
  },
  {
    id: 'platform-satisfaction',
    sectionId: 'day-in-life',
    type: 'scale',
    title: 'How satisfied are you with your current programming setup?',
    description: 'Think about the full workflow: writing, delivering, getting data back, adjusting.',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'Cobbled together, barely works', max: 'Smooth and dialed in' },
    required: true,
  },
  {
    id: 'how-athletes-log',
    sectionId: 'day-in-life',
    type: 'single-choice',
    title: 'How do your athletes log their training?',
    required: true,
    options: [
      { value: 'app', label: 'In an app or platform (they enter sets/reps/weight)' },
      { value: 'shared-sheet', label: 'In a shared spreadsheet' },
      { value: 'send-me', label: 'They send me notes, screenshots, or messages' },
      { value: 'i-log', label: 'I log everything for them during sessions' },
      { value: 'dont-log', label: 'Most of them don\'t log consistently' },
      { value: 'mixed', label: 'It\'s a mix depending on the athlete' },
    ],
  },
  {
    id: 'how-communicate',
    sectionId: 'day-in-life',
    type: 'multi-choice',
    title: 'How do you communicate with athletes between sessions?',
    description: 'Select all that apply.',
    required: true,
    options: [
      { value: 'text', label: 'Text messages' },
      { value: 'instagram-dm', label: 'Instagram DMs' },
      { value: 'email', label: 'Email' },
      { value: 'whatsapp', label: 'WhatsApp' },
      { value: 'coaching-app', label: 'Through a coaching app' },
      { value: 'phone', label: 'Phone calls' },
      { value: 'in-person-only', label: 'Only in person — we don\'t really communicate between sessions' },
    ],
  },
  {
    id: 'hours-programming',
    sectionId: 'day-in-life',
    type: 'single-choice',
    title: 'How much time do you spend writing and adjusting programs each week?',
    required: true,
    options: [
      { value: 'under-2', label: 'Under 2 hours' },
      { value: '2-5', label: '2 - 5 hours' },
      { value: '5-10', label: '5 - 10 hours' },
      { value: '10-15', label: '10 - 15 hours' },
      { value: '15+', label: '15+ hours' },
    ],
  },

  // ── Section 2: Your Athletes ────────────────────────────────────────
  {
    id: 'athlete-types',
    sectionId: 'athletes',
    type: 'multi-choice',
    title: 'What kinds of athletes do you work with? Select all that apply.',
    required: true,
    options: [
      { value: 'competitive-pl', label: 'Competitive powerlifters', description: 'Training for USAPL, USPA, or other federation meets' },
      { value: 'first-meet', label: 'First-meet athletes', description: 'Preparing for their first competition' },
      { value: 'recreational-lifters', label: 'Recreational lifters', description: 'Barbell training for fitness, not competition' },
      { value: 'general-fitness', label: 'General fitness clients', description: 'Not specifically barbell-focused' },
      { value: 'sport-athletes', label: 'Sport athletes', description: 'Training for a sport other than powerlifting' },
      { value: 'rehab-rtl', label: 'Rehab / return-to-lifting', description: 'Injured athletes working back to full training' },
      { value: 'masters', label: 'Masters lifters (40+)' },
      { value: 'juniors', label: 'Junior / teen lifters' },
    ],
  },
  {
    id: 'athlete-experience-range',
    sectionId: 'athletes',
    type: 'single-choice',
    title: 'What\'s the typical experience level of your athletes?',
    required: true,
    options: [
      { value: 'mostly-beginners', label: 'Mostly beginners (< 1 year training)' },
      { value: 'mostly-intermediate', label: 'Mostly intermediate (1-3 years)' },
      { value: 'mostly-advanced', label: 'Mostly advanced (3+ years, competitive)' },
      { value: 'wide-range', label: 'Wide range — beginners through advanced' },
    ],
  },
  {
    id: 'athlete-tech-comfort',
    sectionId: 'athletes',
    type: 'scale',
    title: 'How tech-savvy are your athletes in general?',
    description: 'Would they comfortably use an app to log training, watch demo videos, and track progress?',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'They\'d struggle with anything beyond texting', max: 'They\'d love a polished app' },
    required: true,
  },
  {
    id: 'athlete-self-accountability',
    sectionId: 'athletes',
    type: 'single-choice',
    title: 'How self-directed are your remote athletes?',
    description: 'When you\'re not standing next to them, do they follow the program and log honestly?',
    condition: {
      questionId: 'in-person-vs-remote',
      operator: 'not-equals',
      value: 'all-in-person',
    },
    required: true,
    options: [
      { value: 'very', label: 'Very — they\'re disciplined and consistent' },
      { value: 'mostly', label: 'Mostly good, but I have to check in on some' },
      { value: 'hit-miss', label: 'Hit or miss — compliance varies a lot' },
      { value: 'struggle', label: 'It\'s a real struggle to keep them accountable' },
    ],
  },

  // ── Section 3: Programming & Methodology ────────────────────────────
  {
    id: 'program-design-approach',
    sectionId: 'programming',
    type: 'single-choice',
    title: 'How do you approach program design?',
    required: true,
    options: [
      { value: 'fully-individual', label: 'Fully individualized', description: 'Every athlete gets a unique program from scratch' },
      { value: 'template-then-modify', label: 'Start from a template, then individualize', description: 'Base templates adjusted per athlete' },
      { value: 'tiered-groups', label: 'Group programs with individual tweaks', description: 'A few programs for different levels, modified as needed' },
      { value: 'depends', label: 'Depends on the athlete and context' },
    ],
  },
  {
    id: 'load-prescription',
    sectionId: 'programming',
    type: 'multi-choice',
    title: 'How do you prescribe training loads?',
    description: 'Select all methods you use regularly.',
    required: true,
    options: [
      { value: 'percentage-1rm', label: 'Percentage of 1RM' },
      { value: 'rpe', label: 'RPE (Rate of Perceived Exertion)' },
      { value: 'rir', label: 'RIR (Reps in Reserve)' },
      { value: 'velocity-targets', label: 'Velocity targets (VBT)', description: 'Prescribe based on bar speed ranges' },
      { value: 'autoregulated-ranges', label: 'Autoregulated ranges', description: 'Work up to an RPE, adjust from there' },
      { value: 'fixed-weight', label: 'Fixed weight / progressive overload', description: 'Add weight each session or week' },
    ],
  },
  {
    id: 'periodization-style',
    sectionId: 'programming',
    type: 'multi-choice',
    title: 'What periodization approaches do you use?',
    description: 'Select all that apply to your current programming.',
    required: true,
    options: [
      { value: 'block', label: 'Block periodization', description: 'Hypertrophy → Strength → Peaking blocks' },
      { value: 'dup', label: 'Daily Undulating (DUP)', description: 'Varying intensity/volume day to day' },
      { value: 'weekly-undulating', label: 'Weekly undulating' },
      { value: 'linear', label: 'Linear progression' },
      { value: 'conjugate', label: 'Conjugate / Westside' },
      { value: 'apre', label: 'APRE (Autoregulatory Progressive Resistance)' },
      { value: 'rpe-based', label: 'RPE-based progressive overload' },
      { value: 'custom', label: 'My own hybrid approach' },
    ],
  },
  {
    id: 'vbt-usage',
    sectionId: 'programming',
    type: 'single-choice',
    title: 'Do you use Velocity-Based Training (VBT) in your coaching?',
    required: true,
    options: [
      { value: 'core-tool', label: 'Yes — it\'s a core part of my programming', description: 'I use velocity data to autoregulate and make real-time load decisions' },
      { value: 'sometimes', label: 'Sometimes — for specific athletes or phases' },
      { value: 'experimenting', label: 'I\'m experimenting with it' },
      { value: 'interested', label: 'Interested but haven\'t started yet' },
      { value: 'no', label: 'No, I don\'t use VBT' },
    ],
  },
  {
    id: 'vbt-devices',
    sectionId: 'programming',
    type: 'multi-choice',
    title: 'Which VBT device(s) do you use?',
    condition: {
      questionId: 'vbt-usage',
      operator: 'includes',
      value: ['core-tool', 'sometimes', 'experimenting'],
    },
    options: [
      { value: 'gymaware', label: 'GymAware / FLEX' },
      { value: 'repone', label: 'RepOne' },
      { value: 'enode', label: 'Enode Pro' },
      { value: 'vitruve', label: 'Vitruve' },
      { value: 'tendo', label: 'Tendo Unit' },
      { value: 'push-band', label: 'PUSH Band' },
      { value: 'metric-vbt', label: 'Metric VBT' },
      { value: 'phone-app', label: 'Phone app (MyLift, etc.)' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'vbt-dream',
    sectionId: 'programming',
    type: 'textarea',
    title: 'If a platform could do anything with your VBT data, what would you want?',
    description: 'Think about auto-load adjustment, velocity profiles, fatigue tracking, load-velocity curves, etc.',
    placeholder: 'e.g. Auto-adjust prescribed load when velocity drops below threshold, build velocity profiles per lift over time...',
    condition: {
      questionId: 'vbt-usage',
      operator: 'includes',
      value: ['core-tool', 'sometimes', 'experimenting'],
    },
  },

  // ── Section 4: Competition & Meet Prep ──────────────────────────────
  {
    id: 'coaches-competitors',
    sectionId: 'comp-prep',
    type: 'single-choice',
    title: 'How many of your athletes compete in powerlifting meets?',
    required: true,
    options: [
      { value: 'all-most', label: 'All or most of them' },
      { value: 'about-half', label: 'About half' },
      { value: 'a-few', label: 'A few — most are recreational' },
      { value: 'none', label: 'None currently' },
    ],
  },
  {
    id: 'meet-prep-tracking',
    sectionId: 'comp-prep',
    type: 'multi-choice',
    title: 'What do you currently track during a meet prep cycle?',
    description: 'Select all that apply.',
    condition: {
      questionId: 'coaches-competitors',
      operator: 'includes',
      value: ['all-most', 'about-half', 'a-few'],
    },
    options: [
      { value: 'peaking-block', label: 'Peaking block programming', description: 'Structured taper and peak' },
      { value: 'openers', label: 'Opener selection and attempt planning' },
      { value: 'bodyweight', label: 'Bodyweight / weight class management' },
      { value: 'training-maxes', label: 'Training maxes and estimated 1RMs' },
      { value: 'velocity-peaks', label: 'Velocity at competition loads', description: 'Using VBT to gauge readiness' },
      { value: 'warmup-plan', label: 'Warmup timing and logistics' },
      { value: 'rpe-trends', label: 'RPE trends going into the meet' },
      { value: 'nothing-formal', label: 'Nothing formal — mostly in my head' },
    ],
  },
  {
    id: 'game-day-pain',
    sectionId: 'comp-prep',
    type: 'textarea',
    title: 'What\'s the hardest part of managing meet day from a coaching standpoint?',
    placeholder: 'e.g. Juggling multiple lifters on the same flight, tracking attempts across platforms, warmup timing...',
    condition: {
      questionId: 'coaches-competitors',
      operator: 'includes',
      value: ['all-most', 'about-half', 'a-few'],
    },
  },
  {
    id: 'meet-day-wish',
    sectionId: 'comp-prep',
    type: 'textarea',
    title: 'If you had a magic tool for meet day, what would it do?',
    placeholder: 'e.g. Auto-calculate 2nd/3rd attempts based on opener performance, warmup countdown timer, flight position tracker...',
    condition: {
      questionId: 'coaches-competitors',
      operator: 'includes',
      value: ['all-most', 'about-half', 'a-few'],
    },
  },

  // ── Section 5: What's Broken Today ──────────────────────────────────
  {
    id: 'biggest-time-sinks',
    sectionId: 'pain',
    type: 'multi-choice',
    title: 'What eats the most of your non-coaching time?',
    description: 'Select your top time sinks — the admin work that takes away from actual coaching.',
    required: true,
    options: [
      { value: 'writing-programs', label: 'Writing / copying / adjusting programs' },
      { value: 'manual-load-calc', label: 'Calculating loads, percentages, velocity targets' },
      { value: 'chasing-athletes', label: 'Chasing athletes for training logs or check-ins' },
      { value: 'scheduling', label: 'Scheduling and coordinating sessions' },
      { value: 'billing', label: 'Invoicing, payment follow-ups' },
      { value: 'data-entry', label: 'Entering or organizing training data' },
      { value: 'switching-tools', label: 'Switching between too many apps and tools' },
      { value: 'content-creation', label: 'Creating content (social media, blog, newsletter)' },
      { value: 'meet-logistics', label: 'Meet prep logistics and coordination' },
    ],
  },
  {
    id: 'biggest-frustration',
    sectionId: 'pain',
    type: 'textarea',
    title: 'Describe your single biggest frustration with how you manage your coaching business right now.',
    description: 'Be specific. Think about the moment where you think "there has to be a better way."',
    placeholder: 'e.g. I spend 2 hours every Sunday copying programs into Google Sheets and then texting links to 12 different athletes...',
    required: true,
  },
  {
    id: 'data-gaps',
    sectionId: 'pain',
    type: 'multi-choice',
    title: 'What data do you wish you had but currently don\'t?',
    description: 'Select all that apply.',
    required: true,
    options: [
      { value: 'long-term-strength', label: 'Long-term strength trends per athlete', description: 'How their squat/bench/deadlift has progressed over months/years' },
      { value: 'velocity-profiles', label: 'Velocity profiles and load-velocity curves' },
      { value: 'volume-load-tracking', label: 'Cumulative volume and load tracking', description: 'Total tonnage, set counts, intensity distribution' },
      { value: 'compliance-rates', label: 'Training compliance / adherence rates', description: 'Are they actually doing what I program?' },
      { value: 'rpe-accuracy', label: 'RPE accuracy over time', description: 'How well their RPE correlates with actual performance' },
      { value: 'bodyweight-history', label: 'Bodyweight and weight class tracking' },
      { value: 'injury-history', label: 'Injury history and modification patterns' },
      { value: 'all-in-one-dashboard', label: 'Just... everything in one place instead of scattered across apps' },
    ],
  },
  {
    id: 'tried-and-abandoned',
    sectionId: 'pain',
    type: 'textarea',
    title: 'Have you tried any coaching platforms or tools before and abandoned them? What went wrong?',
    placeholder: 'e.g. Tried TrainHeroic but it was too rigid for how I program. Used TrueCoach but athletes didn\'t like the UI...',
  },

  // ── Section 6: Your Dream Platform ──────────────────────────────────
  {
    id: 'must-haves',
    sectionId: 'dream-platform',
    type: 'multi-choice',
    title: 'Which capabilities are absolute must-haves?',
    description: 'Select everything that\'s non-negotiable. If a platform doesn\'t have this, you\'re not interested.',
    required: true,
    options: [
      { value: 'program-builder', label: 'Program builder / workout designer', description: 'Build structured programs with sets, reps, load prescription' },
      { value: 'athlete-logging', label: 'Athlete self-logging', description: 'Athletes log their own training via app' },
      { value: 'vbt-integration', label: 'VBT device integration', description: 'Connect velocity trackers, use data in programming' },
      { value: 'rpe-rir-support', label: 'RPE / RIR prescription support', description: 'Prescribe and track by perceived exertion' },
      { value: 'mobile-app', label: 'Mobile app for athletes', description: 'Native or responsive app athletes use in the gym' },
      { value: 'progress-analytics', label: 'Progress analytics and charts', description: 'Visual strength trends, PR tracking, volume analysis' },
      { value: 'remote-delivery', label: 'Remote program delivery', description: 'Send programs to remote athletes with check-in capability' },
      { value: 'exercise-library', label: 'Exercise library with videos', description: 'Attach demo videos to exercises in programs' },
      { value: 'template-system', label: 'Reusable program templates', description: 'Save and reuse program structures across athletes' },
      { value: 'client-management', label: 'Client management / profiles', description: 'Centralized athlete profiles with history and notes' },
      { value: 'comp-prep-tools', label: 'Competition prep tools', description: 'Attempt planning, weight class tracking, meet day management' },
      { value: 'messaging', label: 'In-app messaging with athletes' },
    ],
  },
  {
    id: 'nice-to-haves',
    sectionId: 'dream-platform',
    type: 'multi-choice',
    title: 'Which of these would be great bonuses but aren\'t dealbreakers?',
    options: [
      { value: 'branded-app', label: 'White-label / branded athlete app', description: 'Athletes see your brand, not a third-party name' },
      { value: 'payment-billing', label: 'Built-in payment and billing' },
      { value: 'scheduling', label: 'Session scheduling / booking' },
      { value: 'template-marketplace', label: 'Sell programs / templates', description: 'Revenue from digital products' },
      { value: 'readiness-wellness', label: 'Daily readiness / wellness surveys', description: 'Sleep, soreness, stress check-ins' },
      { value: 'nutrition-tracking', label: 'Nutrition or macro tracking' },
      { value: 'community-features', label: 'Community features', description: 'Leaderboards, group challenges, shared PRs' },
      { value: 'video-form-review', label: 'Video form check / review', description: 'Athletes upload videos, you provide feedback' },
      { value: 'automated-deloads', label: 'Automated deload / fatigue management', description: 'Platform suggests deloads based on accumulated fatigue' },
      { value: 'bodyweight-tracking', label: 'Bodyweight and body composition tracking' },
    ],
  },
  {
    id: 'dealbreakers',
    sectionId: 'dream-platform',
    type: 'textarea',
    title: 'Are there any absolute dealbreakers that would make you reject a platform?',
    placeholder: 'e.g. If it doesn\'t support RPE-based programming I won\'t use it. If the athlete app looks terrible they won\'t log...',
  },
  {
    id: 'mobile-importance',
    sectionId: 'dream-platform',
    type: 'scale',
    title: 'How important is the athlete mobile experience?',
    description: 'Think about what your athletes need to do: view workouts, log sets, watch demos, message you.',
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: 'Desktop is fine', max: 'Mobile-first is everything' },
    required: true,
  },

  // ── Section 7: Business & Growth ────────────────────────────────────
  {
    id: 'revenue-model',
    sectionId: 'business',
    type: 'multi-choice',
    title: 'How do you currently generate revenue? Select all that apply.',
    required: true,
    options: [
      { value: 'per-session', label: 'Per-session training fees' },
      { value: 'monthly-retainer', label: 'Monthly coaching retainer' },
      { value: 'program-sales', label: 'Program / template sales' },
      { value: 'group-classes', label: 'Group session fees' },
      { value: 'online-coaching', label: 'Online coaching packages' },
      { value: 'meet-handling', label: 'Meet handling / game-day coaching fees' },
      { value: 'education', label: 'Clinics, workshops, or educational content' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'growth-goals',
    sectionId: 'business',
    type: 'multi-choice',
    title: 'What are your growth goals over the next 12 months?',
    description: 'Select all that apply.',
    required: true,
    options: [
      { value: 'more-remote', label: 'Take on more remote athletes', description: 'Scale beyond local geography' },
      { value: 'more-in-person', label: 'Grow in-person clientele' },
      { value: 'sell-templates', label: 'Sell programming templates at scale', description: 'Passive revenue from digital products' },
      { value: 'build-brand', label: 'Build the Cannoli Gang brand', description: 'More content, larger audience, community' },
      { value: 'streamline-ops', label: 'Streamline operations', description: 'Spend less time on admin, more on coaching' },
      { value: 'add-coaches', label: 'Bring on additional coaches' },
      { value: 'open-facility', label: 'Open or expand to my own facility' },
      { value: 'better-athlete-results', label: 'Produce better athlete results', description: 'More state records, national qualifiers' },
    ],
  },
  {
    id: 'monthly-budget',
    sectionId: 'business',
    type: 'single-choice',
    title: 'What would you realistically spend per month on coaching software?',
    description: 'Think about what you\'d pay if the tool genuinely saved you hours every week.',
    required: true,
    options: [
      { value: 'free-only', label: 'Only free tools' },
      { value: 'under-30', label: 'Up to $30/mo' },
      { value: '30-75', label: '$30 - $75/mo' },
      { value: '75-150', label: '$75 - $150/mo' },
      { value: '150-300', label: '$150 - $300/mo' },
      { value: '300+', label: '$300+/mo if it truly replaces multiple tools' },
    ],
  },
  {
    id: 'pricing-model-pref',
    sectionId: 'business',
    type: 'single-choice',
    title: 'Which pricing model works best for you?',
    required: true,
    options: [
      { value: 'flat-rate', label: 'Flat monthly rate', description: 'One price regardless of athlete count' },
      { value: 'per-athlete', label: 'Per-athlete pricing', description: 'Scales with your roster' },
      { value: 'tiered', label: 'Tiered feature plans', description: 'Basic, Pro, etc.' },
      { value: 'pay-as-you-go', label: 'Pay-as-you-go / credit-based' },
      { value: 'no-preference', label: 'No preference' },
    ],
  },

  // ── Section 8: Priorities & Tradeoffs ───────────────────────────────
  {
    id: 'top-priorities',
    sectionId: 'priorities',
    type: 'ranking',
    title: 'Rank these in order of importance to you.',
    description: 'Drag or use arrows to reorder. Top item = highest priority.',
    required: true,
    options: [
      { value: 'save-time', label: 'Save me time on programming and admin' },
      { value: 'better-data', label: 'Give me better data on my athletes' },
      { value: 'athlete-experience', label: 'Give my athletes a better experience' },
      { value: 'vbt-integration', label: 'Integrate with VBT devices seamlessly' },
      { value: 'grow-business', label: 'Help me grow my business and revenue' },
      { value: 'comp-prep', label: 'Make competition prep easier' },
      { value: 'affordable', label: 'Be affordable for a solo coach' },
      { value: 'simple', label: 'Be simple — I don\'t want complexity' },
    ],
  },
  {
    id: 'timeline',
    sectionId: 'priorities',
    type: 'single-choice',
    title: 'How urgently are you looking for a platform?',
    required: true,
    options: [
      { value: 'yesterday', label: 'Yesterday — I need this now' },
      { value: '1-3-months', label: 'Within 1-3 months' },
      { value: '3-6-months', label: 'Within 3-6 months' },
      { value: 'exploring', label: 'Just exploring what\'s out there' },
    ],
  },
  {
    id: 'final-thoughts',
    sectionId: 'priorities',
    type: 'textarea',
    title: 'Anything else we should know?',
    description: 'Frustrations, wishes, ideas, rants — anything that helps us understand what you need.',
    placeholder: 'This is your open mic. Say whatever\'s on your mind about your coaching tools and workflow...',
  },
];
