/**
 * Powerlifting tags for exercises in the exercise library.
 *
 * Tag categories:
 * - competition_lift: SBD competition movements
 * - competition_variation: Close variations used in peaking/specificity blocks
 * - accessory: Supporting exercises for SBD development
 * - gpp: General physical preparedness (cardio, core, conditioning)
 *
 * Additional descriptive tags:
 * - squat, bench, deadlift: which competition lift it supports
 * - upper_body, lower_body: broad category
 * - push, pull, hinge, carry: movement pattern
 * - core, arms, shoulders: muscle group focus
 * - unilateral: single-limb
 * - machine: machine-based
 * - tempo, paused: tempo/pause variations
 */

// ============================================================
// Powerlifting tag assignments for free-exercise-db exercises
// Maps exercise name (from free-exercise-db) -> tags array
// ============================================================

export const freeExerciseDbTags: Record<string, string[]> = {
  // --- Competition lifts & close variations already in free-exercise-db ---
  'Barbell Squat': ['competition_lift', 'squat', 'lower_body'],
  'Barbell Full Squat': ['competition_variation', 'squat', 'lower_body'],
  'Barbell Deadlift': ['competition_lift', 'deadlift', 'lower_body', 'hinge'],
  'Sumo Deadlift': ['competition_lift', 'deadlift', 'lower_body', 'hinge'],
  'Barbell Bench Press - Medium Grip': ['competition_lift', 'bench', 'upper_body', 'push'],

  // --- Squat variations ---
  'Front Squat (Clean Grip)': ['competition_variation', 'squat', 'lower_body'],
  'Front Barbell Squat': ['competition_variation', 'squat', 'lower_body'],
  'Front Barbell Squat To A Bench': ['competition_variation', 'squat', 'lower_body'],
  'Box Squat': ['competition_variation', 'squat', 'lower_body'],
  'Box Squat with Bands': ['competition_variation', 'squat', 'lower_body'],
  'Box Squat with Chains': ['competition_variation', 'squat', 'lower_body'],
  'Goblet Squat': ['accessory', 'squat', 'lower_body'],
  'Hack Squat': ['accessory', 'squat', 'lower_body', 'machine'],
  'Barbell Hack Squat': ['accessory', 'squat', 'lower_body'],
  'Olympic Squat': ['competition_variation', 'squat', 'lower_body'],
  'Narrow Stance Squats': ['competition_variation', 'squat', 'lower_body'],
  'Speed Box Squat': ['competition_variation', 'squat', 'lower_body'],
  'Reverse Band Box Squat': ['competition_variation', 'squat', 'lower_body'],
  'Reverse Band Power Squat': ['competition_variation', 'squat', 'lower_body'],
  'Kneeling Squat': ['accessory', 'squat', 'lower_body'],
  'Bodyweight Squat': ['gpp', 'squat', 'lower_body'],
  'Dumbbell Squat': ['accessory', 'squat', 'lower_body'],
  'Overhead Squat': ['accessory', 'squat', 'lower_body'],
  'Barbell Side Split Squat': ['accessory', 'squat', 'lower_body', 'unilateral'],
  'Smith Machine Squat': ['accessory', 'squat', 'lower_body', 'machine'],
  'Jefferson Squats': ['accessory', 'squat', 'lower_body'],
  'Freehand Jump Squat': ['gpp', 'squat', 'lower_body'],
  'Barbell Squat To A Bench': ['competition_variation', 'squat', 'lower_body'],

  // --- Bench variations ---
  'Barbell Incline Bench Press - Medium Grip': ['accessory', 'bench', 'upper_body', 'push'],
  'Decline Barbell Bench Press': ['accessory', 'bench', 'upper_body', 'push'],
  'Close-Grip Barbell Bench Press': ['competition_variation', 'bench', 'upper_body', 'push'],
  'Dumbbell Bench Press': ['accessory', 'bench', 'upper_body', 'push'],
  'Incline Dumbbell Press': ['accessory', 'bench', 'upper_body', 'push'],
  'Decline Dumbbell Bench Press': ['accessory', 'bench', 'upper_body', 'push'],
  'Flat Bench Cable Flyes': ['accessory', 'bench', 'upper_body', 'push'],
  'Incline Cable Flye': ['accessory', 'bench', 'upper_body', 'push'],
  'Push-Ups': ['accessory', 'bench', 'upper_body', 'push'],
  'Wide-Grip Barbell Bench Press': ['competition_variation', 'bench', 'upper_body', 'push'],
  'Reverse Grip Bench Press': ['accessory', 'bench', 'upper_body', 'push'],
  'Floor Press': ['competition_variation', 'bench', 'upper_body', 'push'],
  'Board Press': ['competition_variation', 'bench', 'upper_body', 'push'],

  // --- Deadlift variations ---
  'Romanian Deadlift': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
  'Romanian Deadlift With Dumbbells': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Stiff-Legged Barbell Deadlift': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
  'Stiff-Legged Dumbbell Deadlift': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Rack Pull': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
  'Rack Pulls': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
  'Deficit Deadlift': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
  'Trap Bar Deadlift': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Sumo Deadlift with Bands': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],

  // --- Row / Pull ---
  'Barbell Deadlift Row': ['accessory', 'upper_body', 'pull'],
  'Bent Over Barbell Row': ['accessory', 'upper_body', 'pull'],
  'Bent Over Two-Dumbbell Row': ['accessory', 'upper_body', 'pull'],
  'One-Arm Dumbbell Row': ['accessory', 'upper_body', 'pull', 'unilateral'],
  'Seated Cable Rows': ['accessory', 'upper_body', 'pull', 'machine'],
  'T-Bar Row': ['accessory', 'upper_body', 'pull'],
  'T-Bar Row with Handle': ['accessory', 'upper_body', 'pull'],
  'Pendlay Row': ['accessory', 'upper_body', 'pull'],
  'Inverted Row': ['accessory', 'upper_body', 'pull'],
  'Wide-Grip Lat Pulldown': ['accessory', 'upper_body', 'pull', 'machine'],
  'Underhand Cable Pulldowns': ['accessory', 'upper_body', 'pull', 'machine'],
  'Pullups': ['accessory', 'upper_body', 'pull'],
  'Chin-Up': ['accessory', 'upper_body', 'pull'],
  'Band Assisted Pull-Up': ['accessory', 'upper_body', 'pull'],
  'V-Bar Pulldown': ['accessory', 'upper_body', 'pull', 'machine'],

  // --- Overhead press ---
  'Standing Military Press': ['accessory', 'shoulders', 'upper_body', 'push'],
  'Seated Barbell Military Press': ['accessory', 'shoulders', 'upper_body', 'push'],
  'Dumbbell Shoulder Press': ['accessory', 'shoulders', 'upper_body', 'push'],
  'Arnold Dumbbell Press': ['accessory', 'shoulders', 'upper_body', 'push'],

  // --- Legs / posterior chain ---
  'Barbell Lunge': ['accessory', 'squat', 'lower_body', 'unilateral'],
  'Dumbbell Lunges': ['accessory', 'squat', 'lower_body', 'unilateral'],
  'Walking Barbell Lunge': ['accessory', 'squat', 'lower_body', 'unilateral'],
  'Bulgarian Split Squat': ['accessory', 'squat', 'lower_body', 'unilateral'],
  'Leg Press': ['accessory', 'squat', 'lower_body', 'machine'],
  'Leg Extensions': ['accessory', 'squat', 'lower_body', 'machine'],
  'Lying Leg Curls': ['accessory', 'deadlift', 'lower_body', 'machine'],
  'Seated Leg Curl': ['accessory', 'deadlift', 'lower_body', 'machine'],
  'Standing Leg Curl': ['accessory', 'deadlift', 'lower_body', 'machine'],
  'Glute Ham Raise': ['accessory', 'deadlift', 'lower_body'],
  'Hip Thrust': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Barbell Hip Thrust': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Glute Bridge': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Good Morning': ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
  'Seated Good Mornings': ['accessory', 'deadlift', 'lower_body', 'hinge'],
  'Standing Calf Raises': ['gpp', 'lower_body'],
  'Seated Calf Raise': ['gpp', 'lower_body', 'machine'],
  'Nordic Hamstring Curl': ['accessory', 'deadlift', 'lower_body'],

  // --- Arms ---
  'Barbell Curl': ['gpp', 'arms', 'upper_body', 'pull'],
  'Dumbbell Bicep Curl': ['gpp', 'arms', 'upper_body', 'pull'],
  'Hammer Curls': ['gpp', 'arms', 'upper_body', 'pull'],
  'EZ-Bar Curl': ['gpp', 'arms', 'upper_body', 'pull'],
  'Close-Grip EZ Bar Curl': ['gpp', 'arms', 'upper_body', 'pull'],
  'Triceps Pushdown': ['gpp', 'arms', 'upper_body', 'push'],
  'Lying Triceps Press': ['accessory', 'arms', 'upper_body', 'push'],
  'Dips - Triceps Version': ['accessory', 'bench', 'upper_body', 'push'],
  'Tricep Dumbbell Kickback': ['gpp', 'arms', 'upper_body', 'push'],
  'Overhead Triceps Extension': ['gpp', 'arms', 'upper_body', 'push'],

  // --- Lateral raises / shoulders ---
  'Side Lateral Raise': ['gpp', 'shoulders', 'upper_body'],
  'Front Dumbbell Raise': ['gpp', 'shoulders', 'upper_body'],
  'Face Pull': ['accessory', 'shoulders', 'upper_body', 'pull'],

  // --- Core ---
  'Plank': ['gpp', 'core'],
  'Ab Roller': ['gpp', 'core'],
  'Elbow Plank': ['gpp', 'core'],
  'Hanging Leg Raise': ['gpp', 'core'],
  'Dead Bug': ['gpp', 'core'],
  'Pallof Press With Rotation': ['gpp', 'core'],

  // --- Conditioning ---
  'Farmer\'s Walk': ['gpp', 'carry', 'lower_body'],
  'Kettlebell Swing': ['gpp', 'hinge', 'lower_body'],
  'Clean and Jerk': ['accessory', 'lower_body'],
  'Power Clean': ['accessory', 'lower_body', 'hinge'],
  'Box Jump (Multiple Response)': ['gpp', 'lower_body'],

  // --- Powerlifting-specific from free-exercise-db ---
  'Straight-Arm Pulldown': ['accessory', 'upper_body', 'pull', 'machine'],
  'Barbell Shrug': ['gpp', 'upper_body', 'pull'],
  'Hyperextensions (Back Extensions)': ['accessory', 'deadlift', 'lower_body', 'hinge'],
};

// ============================================================
// TeamBuildr exercise name -> free-exercise-db name mapping
// For exercises that have a match but different names
// ============================================================

export const teambuildrToFreeExerciseDb: Record<string, string> = {
  // --- Exact matches (11) - no mapping needed, listed for documentation ---
  // 'Dumbbell Bench Press' -> 'Dumbbell Bench Press'
  // 'Goblet Squat' -> 'Goblet Squat'
  // 'Hack Squat' -> 'Hack Squat'
  // 'Hang Clean' -> 'Hang Clean'
  // 'Incline Dumbbell Press' -> 'Incline Dumbbell Press'
  // 'Inverted Row' -> 'Inverted Row'
  // 'Leg Press' -> 'Leg Press'
  // 'Plank' -> 'Plank'
  // 'Sumo Deadlift' -> 'Sumo Deadlift'
  // 'Trap Bar Deadlift' -> 'Trap Bar Deadlift'
  'Band Assisted Pull-up': 'Band Assisted Pull-Up',
  'Bicep Exercise of choice': 'Bicep Exercise of Choice',

  // --- Name variations that map to existing free-exercise-db entries ---
  'Back Squat': 'Barbell Squat',
  'Barbell Back Squat': 'Barbell Squat',
  'Comp Squat': 'Barbell Squat',
  'high bar squat': 'Barbell Squat',
  'Front Squat': 'Front Barbell Squat',
  'Conventional Deadlift': 'Barbell Deadlift',
  'Comp Deadlift': 'Barbell Deadlift',
  'Deadlift': 'Barbell Deadlift',
  'Barbell Bench Press': 'Barbell Bench Press - Medium Grip',
  'Comp bench': 'Barbell Bench Press - Medium Grip',
  'Barbell Incline Bench Press': 'Barbell Incline Bench Press - Medium Grip',
  'Barbell Row': 'Bent Over Barbell Row',
  '**Barbell Bent Over Row': 'Bent Over Barbell Row',
  'Pronated Barbell Row': 'Bent Over Barbell Row',
  'Pendlay Row': 'Pendlay Row',
  'Pull-Ups': 'Pullups',
  'Push Up': 'Push-Ups',
  'RDL (Romanian Deadlift)': 'Romanian Deadlift',
  'Dumbbell RDL': 'Romanian Deadlift With Dumbbells',
  'Single Arm Dumbbell Row': 'One-Arm Dumbbell Row',
  'Seated Cable Row': 'Seated Cable Rows',
  'Lat Pull-down': 'Wide-Grip Lat Pulldown',
  'Glute Bridge': 'Glute Bridge',
  'Hip Thrust': 'Barbell Hip Thrust',
  'Walking Lunge': 'Walking Barbell Lunge',
  'DB Reverse Lunge': 'Dumbbell Lunges',
  'Leg Extension': 'Leg Extensions',
  'Hamstring Curl': 'Lying Leg Curls',
  'Lying Hamstring Curl': 'Lying Leg Curls',
  'Cable Hamstring Curl': 'Standing Leg Curl',
  'Ab Wheel Rollouts': 'Ab Roller',
  'Dumbbell Hammer Curls': 'Hammer Curls',
  'Alternating DB Hammer Curls': 'Hammer Curls',
  'Seated Hammer Curls': 'Hammer Curls',
  'EZ Bar Curl': 'EZ-Bar Curl',
  'DB Lateral Raises': 'Side Lateral Raise',
  'Seated Lateral Raises': 'Side Lateral Raise',
  'Face Pulls': 'Face Pull',
  'Deadbug': 'Dead Bug',
  'KB Swing': 'Kettlebell Swing',
  'Box Jump': 'Box Jump (Multiple Response)',
  'Nordic Curl': 'Nordic Hamstring Curl',
  'Seated Good Morning': 'Seated Good Mornings',
  'Cable Pallof Press': 'Pallof Press With Rotation',
  'Standing Good Morning': 'Good Morning',
  'Seated Dumbbell Overhead Press': 'Dumbbell Shoulder Press',
  'KB/DB Bulgarian Split Squat': 'Bulgarian Split Squat',
  'Front Foot Elevated Bulgarian Split Squat': 'Bulgarian Split Squat',
  'Tricep Dips': 'Dips - Triceps Version',
  'Rope Overhead Tricep Extension': 'Overhead Triceps Extension',
  'Seated Overhead Triceps Extension': 'Overhead Triceps Extension',
  'GHD Back Extension': 'Hyperextensions (Back Extensions)',
  'Cossack Squat': 'Barbell Side Split Squat',
  'Bicep Curls': 'Dumbbell Bicep Curl',
  'Crossbody DB Hammer Curl': 'Hammer Curls',
  '1 Arm Farmers Carry': 'Farmer\'s Walk',
};

// ============================================================
// TeamBuildr exercises with NO match in free-exercise-db
// These will be created as new exercises during seeding
// ============================================================

export interface NewExerciseEntry {
  name: string;
  category: string;
  tags: string[];
  equipment: string | null;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  force: string | null;
  level: string;
  mechanic: string | null;
}

export const teambuildrNewExercises: NewExerciseEntry[] = [
  // --- Competition lift variations (bench) ---
  {
    name: 'Comp Bench',
    category: 'powerlifting',
    tags: ['competition_lift', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Spoto Press',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: '2 Count Spoto Press',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Larsen Press',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Larsen Press (3 Count Pause)',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Closer Grip Larsen Press',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Touch and Go Larsen Press',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Touch and Go Bench',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Closer Grip Bench',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: '1 Count Paused Bench',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: '2 Count Paused Bench',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: '3 Count Paused Bench',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: '2 Board Bench Press',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Tempo Paused Bench (3-1-0)',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'tempo', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Tempo Paused Bench (3-2-0 Tempo)',
    category: 'powerlifting',
    tags: ['competition_variation', 'bench', 'upper_body', 'push', 'tempo', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Deficit Push-up',
    category: 'strength',
    tags: ['accessory', 'bench', 'upper_body', 'push'],
    equipment: 'body only',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },

  // --- Competition lift variations (squat) ---
  {
    name: 'Comp Squat',
    category: 'powerlifting',
    tags: ['competition_lift', 'squat', 'lower_body'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Paused Squat',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Beltless 2 Count Paused Squat',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back', 'abdominals'],
    force: 'push',
    level: 'advanced',
    mechanic: 'compound',
  },
  {
    name: 'Tempo Paused Squat (3-1-0 Tempo)',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body', 'tempo', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Tempo Paused Squat (2-2-2 Tempo)',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body', 'tempo', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Tempo Paused Squat (3-1-3 tempo)',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body', 'tempo', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'SSB Squat',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Hatfield Squat',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Belt Squat',
    category: 'powerlifting',
    tags: ['accessory', 'squat', 'lower_body', 'machine'],
    equipment: 'machine',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Heavy Squat Walkout',
    category: 'powerlifting',
    tags: ['competition_variation', 'squat', 'lower_body'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes', 'lower back'],
    secondaryMuscles: ['abdominals'],
    force: null,
    level: 'advanced',
    mechanic: 'compound',
  },
  {
    name: 'Heel Elevated Goblet Squat',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body'],
    equipment: 'dumbbell',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
  },
  {
    name: 'Sandbag Squat',
    category: 'strongman',
    tags: ['accessory', 'squat', 'lower_body'],
    equipment: 'other',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['lower back', 'abdominals'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },

  // --- Competition lift variations (deadlift) ---
  {
    name: 'Comp Deadlift',
    category: 'powerlifting',
    tags: ['competition_lift', 'deadlift', 'lower_body', 'hinge'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['quadriceps', 'forearms'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Paused Deadlift',
    category: 'powerlifting',
    tags: ['competition_variation', 'deadlift', 'lower_body', 'hinge', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['quadriceps', 'forearms'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Paused Sumo Deadlift (Off The Floor)',
    category: 'powerlifting',
    tags: ['competition_variation', 'deadlift', 'lower_body', 'hinge', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'quadriceps'],
    secondaryMuscles: ['lower back', 'forearms'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Block Deadlift',
    category: 'powerlifting',
    tags: ['competition_variation', 'deadlift', 'lower_body', 'hinge'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['forearms'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Tempo Deadlift',
    category: 'powerlifting',
    tags: ['competition_variation', 'deadlift', 'lower_body', 'hinge', 'tempo'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['quadriceps', 'forearms'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Controlled Eccentric Deadlift',
    category: 'powerlifting',
    tags: ['competition_variation', 'deadlift', 'lower_body', 'hinge', 'tempo'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['quadriceps', 'forearms'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Paused RDL',
    category: 'powerlifting',
    tags: ['competition_variation', 'deadlift', 'lower_body', 'hinge', 'paused'],
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },

  // --- Squat accessories ---
  {
    name: 'SSB Bulgarian Split Squats',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Front Foot Elevated Split Squat',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'dumbbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Split Squat',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'body only',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
  },
  {
    name: 'Front Rack Reverse Lunge',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Lateral Box Step Up',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'dumbbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Weighted Box Step Up',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'dumbbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Single Leg Extensions',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral', 'machine'],
    equipment: 'machine',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: [],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },
  {
    name: 'Leg Press Calf Raises',
    category: 'strength',
    tags: ['gpp', 'lower_body', 'machine'],
    equipment: 'machine',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },

  // --- Deadlift accessories ---
  {
    name: 'GHD Dumbbell Back Extension',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body', 'hinge'],
    equipment: 'dumbbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: [],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Single Leg RDL',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body', 'hinge', 'unilateral'],
    equipment: 'dumbbell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Single Leg Hip Thrust',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body', 'hinge', 'unilateral'],
    equipment: 'barbell',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Single Leg Hamstring Curl',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body', 'unilateral', 'machine'],
    equipment: 'machine',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    force: 'pull',
    level: 'beginner',
    mechanic: 'isolation',
  },

  // --- Upper body accessories ---
  {
    name: 'Chest Press Machine',
    category: 'strength',
    tags: ['accessory', 'bench', 'upper_body', 'push', 'machine'],
    equipment: 'machine',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
  },
  {
    name: 'Chest Supported Row',
    category: 'strength',
    tags: ['accessory', 'upper_body', 'pull'],
    equipment: 'dumbbell',
    primaryMuscles: ['middle back'],
    secondaryMuscles: ['biceps', 'lats'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Single Arm Chest Supported Row',
    category: 'strength',
    tags: ['accessory', 'upper_body', 'pull', 'unilateral'],
    equipment: 'dumbbell',
    primaryMuscles: ['middle back'],
    secondaryMuscles: ['biceps', 'lats'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Horizontal Row',
    category: 'strength',
    tags: ['accessory', 'upper_body', 'pull'],
    equipment: 'body only',
    primaryMuscles: ['middle back'],
    secondaryMuscles: ['biceps', 'lats'],
    force: 'pull',
    level: 'beginner',
    mechanic: 'compound',
  },
  {
    name: 'Cable Flyes',
    category: 'strength',
    tags: ['accessory', 'bench', 'upper_body', 'push'],
    equipment: 'cable',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'isolation',
  },
  {
    name: 'Chest Flyes',
    category: 'strength',
    tags: ['accessory', 'bench', 'upper_body', 'push'],
    equipment: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'isolation',
  },
  {
    name: 'Behind the Neck Press',
    category: 'strength',
    tags: ['accessory', 'shoulders', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Landmine Shoulder Press',
    category: 'strength',
    tags: ['accessory', 'shoulders', 'upper_body', 'push'],
    equipment: 'barbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Shoulder Combo',
    category: 'strength',
    tags: ['gpp', 'shoulders', 'upper_body'],
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },
  {
    name: 'Chest Supported Shoulder Combo',
    category: 'strength',
    tags: ['gpp', 'shoulders', 'upper_body'],
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },
  {
    name: 'Tricep Extension',
    category: 'strength',
    tags: ['gpp', 'arms', 'upper_body', 'push'],
    equipment: 'cable',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },

  // --- Core ---
  {
    name: 'GHD Sit-up',
    category: 'strength',
    tags: ['gpp', 'core'],
    equipment: 'body only',
    primaryMuscles: ['abdominals'],
    secondaryMuscles: ['hip flexors'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Side Plank on Elbow',
    category: 'strength',
    tags: ['gpp', 'core'],
    equipment: 'body only',
    primaryMuscles: ['abdominals'],
    secondaryMuscles: ['shoulders'],
    force: null,
    level: 'beginner',
    mechanic: null,
  },
  {
    name: 'Plank Shoulder Taps',
    category: 'strength',
    tags: ['gpp', 'core'],
    equipment: 'body only',
    primaryMuscles: ['abdominals'],
    secondaryMuscles: ['shoulders'],
    force: null,
    level: 'beginner',
    mechanic: null,
  },
  {
    name: 'Trunk Rotation',
    category: 'strength',
    tags: ['gpp', 'core'],
    equipment: 'cable',
    primaryMuscles: ['abdominals'],
    secondaryMuscles: ['obliques'],
    force: 'pull',
    level: 'beginner',
    mechanic: 'isolation',
  },

  // --- Conditioning / GPP ---
  {
    name: 'Assault Bike',
    category: 'cardio',
    tags: ['gpp'],
    equipment: 'machine',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
  },
  {
    name: 'Push/Pull Cardio',
    category: 'cardio',
    tags: ['gpp'],
    equipment: 'machine',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    force: null,
    level: 'beginner',
    mechanic: null,
  },
  {
    name: 'KB Clean',
    category: 'strength',
    tags: ['gpp', 'lower_body', 'hinge'],
    equipment: 'kettlebells',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['forearms', 'shoulders'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },

  // --- Placeholder / open-ended exercises ---
  {
    name: 'Bicep Exercise of Choice',
    category: 'strength',
    tags: ['gpp', 'arms', 'upper_body', 'pull'],
    equipment: null,
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    force: 'pull',
    level: 'beginner',
    mechanic: 'isolation',
  },

  // --- Exercises referenced in teambuildrToFreeExerciseDb but not in free-exercise-db ---
  // These exist as tag targets in freeExerciseDbTags but need actual DB records
  {
    name: 'Bulgarian Split Squat',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'dumbbell',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Glute Bridge',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body', 'hinge'],
    equipment: 'body only',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },
  {
    name: 'Kettlebell Swing',
    category: 'strength',
    tags: ['gpp', 'hinge', 'lower_body'],
    equipment: 'kettlebells',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['shoulders', 'lower back'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Nordic Hamstring Curl',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body'],
    equipment: 'body only',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    force: 'pull',
    level: 'advanced',
    mechanic: 'isolation',
  },
  {
    name: 'Overhead Triceps Extension',
    category: 'strength',
    tags: ['gpp', 'arms', 'upper_body', 'push'],
    equipment: 'cable',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    force: 'push',
    level: 'beginner',
    mechanic: 'isolation',
  },
  {
    name: 'Pendlay Row',
    category: 'strength',
    tags: ['accessory', 'upper_body', 'pull'],
    equipment: 'barbell',
    primaryMuscles: ['middle back'],
    secondaryMuscles: ['biceps', 'lats'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Push-Ups',
    category: 'strength',
    tags: ['accessory', 'bench', 'upper_body', 'push'],
    equipment: 'body only',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
  },
  {
    name: 'Romanian Deadlift With Dumbbells',
    category: 'strength',
    tags: ['accessory', 'deadlift', 'lower_body', 'hinge'],
    equipment: 'dumbbell',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower back'],
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
  },
  {
    name: 'Walking Barbell Lunge',
    category: 'strength',
    tags: ['accessory', 'squat', 'lower_body', 'unilateral'],
    equipment: 'barbell',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    force: 'push',
    level: 'intermediate',
    mechanic: 'compound',
  },
];

// ============================================================
// Non-exercise items from TeamBuildr (notes, surveys, etc.)
// These should be skipped during exercise import
// ============================================================

export const teambuildrNonExercises = new Set([
  "Coach's Note",
  'Note',
  'End of Block Athlete Survey',
  'Movement Assessment',
  'Week RPE',
  'Weekly Peaking Fatigue Assesment',
]);

// ============================================================
// TeamBuildr name normalization for import matching
// Maps TeamBuildr name -> canonical name used in our DB
// Combines both freeExerciseDb mappings and new exercises
// ============================================================

export function resolveTeambuildrExerciseName(tbName: string): string {
  // Check direct mapping to free-exercise-db
  if (tbName in teambuildrToFreeExerciseDb) {
    return teambuildrToFreeExerciseDb[tbName];
  }

  // Normalize casing for specific known exercises
  const caseNormalizations: Record<string, string> = {
    'high bar squat': 'Barbell Squat',
    'Heel elevated goblet squat': 'Heel Elevated Goblet Squat',
    'Single leg hamstring curl': 'Single Leg Hamstring Curl',
    'Comp bench': 'Comp Bench',
  };
  if (tbName in caseNormalizations) {
    return caseNormalizations[tbName];
  }

  // Return as-is (either exact match in DB or new exercise created with this name)
  return tbName;
}
